help:
	@echo

frontend:
	@sh project/frontend.sh

mongodb:
	@sh project/mongodb.sh

catalogue:
	@sh project/catalogue.sh

redis:
	@sh project/redis.sh

user:
	@sh project/user.sh

cart:
	@sh project/cart.sh

mysql:
	@sh project/mysql.sh

shipping:
	@sh project/shipping.sh

payment:
	@sh project/payment.sh

rabbitmq:
	@sh project/rabbitmq.sh
